query Category($id: ID!) {
  category(id: $id) {
    id
    name
    description
    image {
      url
    }
    products {
      id
      name
      description
      categories {
        id
        name
      }
      image {
        url
      }
    }
    posts {
      id
      title
      author
      content
      image {
        url
      }
      categories {
        id
        name
      }
    }
  }
}