query Location($id: ID!) {
  location(id: $id) {
    id
    name
    products {
      id
      name
      description
      categories {
        id
        name
      }
      image {
        url
      }
    }
  }
}